// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPIqDN6cgKfD3nbuMkivoBUEQ0IFiFn3E',
    appId: '1:1001101738327:web:547432f37345271dfdfe12',
    messagingSenderId: '1001101738327',
    projectId: 'laravel-auth-29f2b',
    authDomain: 'laravel-auth-29f2b.firebaseapp.com',
    databaseURL: 'https://laravel-auth-29f2b-default-rtdb.firebaseio.com',
    storageBucket: 'laravel-auth-29f2b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApvrrOSZYQklwO4l6HgJ9AcLYXAmgWNKE',
    appId: '1:1001101738327:android:75c8239455b7ea28fdfe12',
    messagingSenderId: '1001101738327',
    projectId: 'laravel-auth-29f2b',
    databaseURL: 'https://laravel-auth-29f2b-default-rtdb.firebaseio.com',
    storageBucket: 'laravel-auth-29f2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnw7DPoxU9kcDPcZaouBg9hQpm4K6tLpE',
    appId: '1:1001101738327:ios:982d4c3b184f0c72fdfe12',
    messagingSenderId: '1001101738327',
    projectId: 'laravel-auth-29f2b',
    databaseURL: 'https://laravel-auth-29f2b-default-rtdb.firebaseio.com',
    storageBucket: 'laravel-auth-29f2b.appspot.com',
    iosClientId: '1001101738327-o82det6dd7pkb75f3hvgc9h7hc2aeubf.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectoFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnw7DPoxU9kcDPcZaouBg9hQpm4K6tLpE',
    appId: '1:1001101738327:ios:cf8d5496fdfe574bfdfe12',
    messagingSenderId: '1001101738327',
    projectId: 'laravel-auth-29f2b',
    databaseURL: 'https://laravel-auth-29f2b-default-rtdb.firebaseio.com',
    storageBucket: 'laravel-auth-29f2b.appspot.com',
    iosClientId: '1001101738327-k0e611i0kp1ni2a0ilhtkv8mcgpi5a4d.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectoFinal.RunnerTests',
  );
}
